start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER1  PASSWORD1 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER2  PASSWORD2 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER3  PASSWORD3 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER4  PASSWORD4 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER5  PASSWORD5 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER6  PASSWORD6 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER7  PASSWORD7 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER8  PASSWORD8 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER9  PASSWORD9 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER10  PASSWORD10 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER11  PASSWORD11 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER12  PASSWORD12 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER13  PASSWORD13 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER14  PASSWORD14 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER15  PASSWORD15 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER16  PASSWORD16 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER17  PASSWORD17 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER18  PASSWORD18 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER19  PASSWORD19 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER20  PASSWORD20 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER21  PASSWORD21 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER22  PASSWORD22 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER23  PASSWORD23 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444 
::start /B java -classpath out/production/TigerZone com.tigerzone.fall2016server.client.ParameterizedClientMain PLAYER24  PASSWORD24 P1TestGameMoves.txt P2TestGameMoves.txt localhost 4444